name: Deploy to ECR

on:
 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: Dev'
        options: ['Dev']
        required: true
        default: 'Dev' 
jobs:
  
  deploy:
    
    name: Deploy image to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: kamiazya/setup-graphviz@v1

  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_oxygen }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_oxygen }}
        aws-region: eu-west-1
    
    - id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fiter-app
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_oxygen }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_oxygen }}
        aws-region: eu-west-1
    
    - name: installing dependcies
      run: |
       curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
       sudo apt-get install apt-transport-https ca-certificates curl --yes
       sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
       echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
       sudo apt-get update -y
       sudo apt-get install helm kubectl -y
       
    
    
    - name: updating kubeconfig and helm repo
      run: |
       aws eks --region eu-west-1 update-kubeconfig --name oxygen-dev
       helm repo add fiter-apps https://fiter1.github.io/oxygen-helm       
    - name: deploy backend
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
       cd helm
       kubectl config set-context --current --namespace=application
       helm install backend https://raw.githubusercontent.com/FITER1/oxygen-helm-chart/main/packages/fineract-0.1.3.tgz
       helm upgrade -i backend --set fineract-rest.tag=$IMAGE_TAG .
